### ISSUE TITLE
kvo

### ISSUE THREAD

**Issue by huangcheng0908** [xjlove/XJAVPlayer#1]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7f8732e86e60 of class AVPlayerItem was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x7f8735377200> (
<NSKeyValueObservance 0x7f87352a4160: Observer: 0x7f873536ad80, Key path: status, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x7f87352a3c20>
<NSKeyValueObservance 0x7f87352a4280: Observer: 0x7f873536ad80, Key path: loadedTimeRanges, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x7f87352a41c0>
)'

**Comment by xjlove** [comment]
还有监听没有被移除导致的奔溃。。。
